FROM ubuntu/postgres:14-22.04_beta

ENV TZ=UTC
ENV POSTGRES_DB=postgres
#ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update
RUN apt-get -y upgrade

COPY init-user-db.sh /docker-entrypoint-initdb.d/init-user-db.sh

EXPOSE 5432